version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports: 
      - "15672:15672"
      - "5672:5672"

  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
        
  generator:
    build: ./generator
    restart: on-failure
    depends_on:
      - rabbitmq

  ingest:
    build: ./ingest
    restart: on-failure
    depends_on:
      - rabbitmq

  api:
    build: ./api  
    restart: on-failure
    depends_on: 
      - database
    ports:
      - "5000:5000"